### ISSUE TITLE
pymongo.errors.OperationFailure: not authorized on admin to execute command { listDatabases: 1 }

### ISSUE THREAD

**Issue by ballerabdude** [artburkart/mongo-connector-example-setup#1]
Since you are the only person that has an example of your config.json I wanted to ask, why do I keep getting the error below
`pymongo.errors.OperationFailure: not authorized on admin to execute command { listDatabases: 1 } `

`

my config json is below
{
    "__comment__": "Configuration options starting with '__' are disabled",
    "__comment__": "To enable them, remove the preceding '__'",

    "mainAddress": "mongodb://cluster-a0.mlab.com:35828,cluster-a1.mlab.com:35828/admin?replicaSet=rs-cluster",
    "oplogFile": "/var/log/mongo-connector/oplog.timestamp",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 3,
    "continueOnError": false,

    "logging": {
        "type": "stream",
        "__filename": "/var/log/mongo-connector/mongo-connector.log",
        "__format": "%(asctime)s [%(levelname)s] %(name)s:%(lineno)d - %(message)s",
        "__rotationWhen": "D",
        "__rotationInterval": 1,
        "__rotationBackups": 10,

        "__type": "syslog",
        "__host": "localhost:514"
    },

    "authentication": {
        "adminUsername": "oplog-reader",
        "password": "password",
        "__passwordFile": "mongo-connector.pwd"
    },

    "__comment__": "For more information about SSL with MongoDB, please see http://docs.mongodb.org/manual/tutorial/configure-ssl-clients/",
    "__ssl": {
        "__sslCertfile": "Path to certificate to identify the local connection against MongoDB",
        "__sslKeyfile": "Path to the private key for sslCertfile. Not necessary if already included in sslCertfile.",
        "__sslCACerts": "Path to concatenated set of certificate authority certificates to validate the other side of the connection",
        "__sslCertificatePolicy": "Policy for validating SSL certificates provided from the other end of the connection. Possible values are 'required' (require and validate certificates), 'optional' (validate but don't require a certificate), and 'ignored' (ignore certificates)."
    },

    "__fields": ["field1", "field2", "field3"],

    "namespaces": {
        "include": [
            "mydb.jobs",
            "mydb.workflows"
        ]
    },

    "docManagers": [
        {
            "docManager": "solr_doc_manager",
            "targetURL": "http://192.168.99.100:8983/solr/gettingstarted",
            "__bulkSize": 1000,
            "__uniqueKey": "_id",
            "__autoCommitInterval": null
        }
    ]
}

`

**Comment by sagargit2** [comment]
You need to create a `oplog-user` in the **admin database** and use the connection string of **local database.'**
All the instructions are provided in mLab docs here [Accessing the MongoDB oplog](http://docs.mlab.com/oplog/#for-deployments-running-mongodb-v26-or-higher)
